#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    if [ -x "/bin/systemctl" ]; then
        systemctl daemon-reload
        systemctl enable btrfs-monitor.service
        if systemctl is-active --quiet btrfs-monitor.service; then
            systemctl restart btrfs-monitor.service
        else
            systemctl start btrfs-monitor.service
        fi
    fi
fi

#DEBHELPER#
